route:
  group_by: ['action']
  group_wait: 10s                  # When an alert is received, wait for thirty seconds to see if there are more alerts. If there are, send them out together.
  group_interval: 10s              # Alert sending interval time
  repeat_interval: 1h              # Repeat alert interval time
  receiver: 'webhook'              # Default


  routes:
  - match:
      action: AutoScaling
    receiver: 'webhook-AutoScaling'
    continue: true
    
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://10.0.253.201:5000/webhook-default'

- name: 'webhook-AutoScaling'
  webhook_configs:
  - url: 'http://10.0.253.201:5000/webhook'

